apiVersion: apps/v1
kind: Deployment
metadata:
  name: test
  namespace: test-deployment
spec:
  selector:
    matchLabels:
      component: tool
  replicas: 1
  template:
    metadata:
      labels:
        component: tool
    spec:
      containers:
      - name: envar-demo-container
        image: gcr.io/google-samples/node-hello:1.0
        env:
        - name: DEMO_GREETINGS
          value: "Hello from the environment"
        - name: DEMO_FAREWELL
          value: "Such a sweet sorrow"
